[package]
name = "dcr-math"
version = "0.1.0"
type = "lib"
description = "Test math lib"
author = "Dexoron"
homepage = "https://dcr.dexoron.su"
license = "MIT"
repository = "https://github.com/dexoron/dcr-test-lib-index"

[build]
language = "c"
standard = "c11"
compiler = "clang"
kind = "staticlib"

[dependencies]
